version: 2
jobs:
   build:
     docker:
       - image: node:latest
     working_directory: /root/ethereum
     steps:
       - checkout
       - run: echo "start config!"
       - run:
           name: dependencies
           command: |
             npm install -g truffle
             pwd
             truffle init
       - run:
           name: open zeppelin
           command: |
             npm init -f
             npm install zeppelin-solidity --save
       - run:
           name: compile
           command: |
             truffle compile
             ls -la
       - run:
           name: test
           command: |
             truffle test ./cocoCoin/test/cococoin.js
       
       
# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8.1.4
#     working_directory: ~/contracts
#     steps:
#       - checkout
#       - run:
#           name: dependencies
#           command: |
#             yarn
#             yarn truffle install
#       - run:
#           name: compile
#           command: yarn truffle compile
#       - run:
#           name: lint
#           command: |
#             yarn run eslint .
#             yarn run solium -- --dir ./contracts
#       - run:
#           name: test
#           command: yarn test:all
#
