version: 2
jobs:
   build: #単体テストを実行するジョブ
     docker:
       - image: node:latest
       - image: docker
     working_directory: /root/ethereum
     steps:
       - checkout
       - run: echo "start config!"
       - run:
           name: dependencies
           command: |
             npm install -g truffle
             pwd
             truffle init
       - run:
           name: open zeppelin
           command: |
             npm init -f
             npm install zeppelin-solidity --save
       - run:
           name: compile
           command: |
             cd cocoCoin
             truffle compile
             ls -la
       - run:
           name: test
           command: |
             cd cocoCoin
             truffle test
#            truffle test ./test/cococoin.js
       - run: echo "start docker check!"
       - run:
           name: docker install
           command: |
             npm install -g docker
             docker --version
             docker ps -a
       
       

#     deploy: #デプロイするジョブ
#     docker:
#     - image: docker
#     working_directory: /root/ethereum
#     steps:
#      - checkout
#      - run: echo "start docker check!"
#      - run: docker --version
#      - run: docker ps -a
#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#      - build
#      - deploy: # deployはbuildのあとに実行
#          requires:
#            - build
#          filters: # eth3ブランチの場合のみデプロイする
#            branches:
#              only: eth3
