version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     working_directory: ~/ethereum/nanaCoin
     steps:
       - checkout
       - run: echo "start config!"
       - run:
           name: dependencies
           command: |
             npm install -g truffle
             mkdir nanaCoin
             cd nanaCoin
             truffle init
#       - run:
#           name: compile
#           command: yarn truffle compile
       
       
# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8.1.4
#     working_directory: ~/contracts
#     steps:
#       - checkout
#       - run:
#           name: dependencies
#           command: |
#             yarn
#             yarn truffle install
#       - run:
#           name: compile
#           command: yarn truffle compile
#       - run:
#           name: lint
#           command: |
#             yarn run eslint .
#             yarn run solium -- --dir ./contracts
#       - run:
#           name: test
#           command: yarn test:all
#
