version: 2
jobs:
   build: #単体テストを実行するジョブ
     docker:
       - image: node:latest
     working_directory: /root/ethereum
     steps:
       - checkout
       - run: echo "start config!"
       - run:
           name: dependencies
           command: |
             npm install -g truffle
             pwd
             truffle init
       - run:
           name: open zeppelin
           command: |
             npm init -f
             npm install zeppelin-solidity --save
       - run:
           name: compile
           command: |
             cd cocoCoin
             truffle compile
             ls -la
       - run:
           name: test
           command: |
             cd cocoCoin
             truffle test
#            truffle test ./test/cococoin.js
   deploy: #デプロイするジョブ
     machine: true
     working_directory: /root/ethereum
     steps:
#       - checkout
      - run: echo "start docker check!"
      - run: docker --version
      - run: docker ps -a
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy: # deployはbuildのあとに実行
#          requires:
#            - build
#          filters: # developブランチの場合のみデプロイする
#            branches:
#              only: develop
